CREATE TABLE shop_supplier_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name varchar(200) NOT NULL,
    supplier_reference varchar(100),
    status varchar(20) NOT NULL DEFAULT 'ORDERED',
    received_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_shop_supplier_order_status CHECK (status IN ('ORDERED', 'RECEIVED')),
    CONSTRAINT ck_shop_supplier_order_supplier CHECK (char_length(trim(supplier_name)) > 0)
);

CREATE TABLE shop_supplier_order_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES shop_supplier_orders(id) ON DELETE CASCADE,
    variant_id bigint NOT NULL,
    product_name varchar(200) NOT NULL,
    variant_name varchar(160),
    sku varchar(100) NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT ck_shop_supplier_line_quantity CHECK (quantity > 0),
    CONSTRAINT uk_shop_supplier_order_variant UNIQUE (order_id, variant_id)
);

CREATE INDEX idx_shop_supplier_order_status_created
    ON shop_supplier_orders (status, created_at);
