CREATE SEQUENCE IF NOT EXISTS shop_order_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE shop_product_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    slug varchar(180) NOT NULL,
    description varchar(2000),
    active boolean NOT NULL DEFAULT true,
    display_order integer NOT NULL DEFAULT 0,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_shop_category_slug UNIQUE (slug),
    CONSTRAINT ck_shop_category_display_order CHECK (display_order >= 0)
);

CREATE INDEX idx_shop_category_active_order
    ON shop_product_categories (active, display_order, name);

CREATE TABLE shop_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    slug varchar(220) NOT NULL,
    description varchar(5000),
    active boolean NOT NULL DEFAULT false,
    display_order integer NOT NULL DEFAULT 0,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_shop_product_slug UNIQUE (slug),
    CONSTRAINT ck_shop_product_display_order CHECK (display_order >= 0)
);

CREATE INDEX idx_shop_product_active_order
    ON shop_products (active, display_order, name);

CREATE TABLE shop_product_category_links (
    product_id bigint NOT NULL REFERENCES shop_products(id) ON DELETE CASCADE,
    category_id bigint NOT NULL REFERENCES shop_product_categories(id) ON DELETE RESTRICT,
    PRIMARY KEY (product_id, category_id)
);

CREATE INDEX idx_shop_product_category_category
    ON shop_product_category_links (category_id, product_id);

CREATE TABLE shop_product_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES shop_products(id) ON DELETE CASCADE,
    sku varchar(100) NOT NULL,
    label varchar(160),
    active boolean NOT NULL DEFAULT true,
    display_order integer NOT NULL DEFAULT 0,
    price_amount_cents bigint NOT NULL,
    price_currency char(3) NOT NULL,
    stock_tracked boolean NOT NULL DEFAULT false,
    stock_on_hand bigint,
    stock_reserved bigint NOT NULL DEFAULT 0,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_shop_variant_sku UNIQUE (sku),
    CONSTRAINT ck_shop_variant_display_order CHECK (display_order >= 0),
    CONSTRAINT ck_shop_variant_price CHECK (price_amount_cents >= 0),
    CONSTRAINT ck_shop_variant_currency CHECK (char_length(price_currency) = 3),
    CONSTRAINT ck_shop_variant_stock CHECK (
        (stock_tracked = false AND stock_on_hand IS NULL AND stock_reserved = 0)
        OR (stock_tracked = true AND stock_on_hand IS NOT NULL
            AND stock_on_hand >= 0 AND stock_reserved >= 0 AND stock_reserved <= stock_on_hand)
    )
);

CREATE INDEX idx_shop_variant_product_active_order
    ON shop_product_variants (product_id, active, display_order);

CREATE TABLE shop_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number varchar(40) NOT NULL,
    customer_user_id bigint NOT NULL,
    status varchar(32) NOT NULL,
    total_amount_cents bigint NOT NULL,
    total_currency char(3) NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_shop_order_number UNIQUE (order_number),
    CONSTRAINT ck_shop_order_total CHECK (total_amount_cents >= 0),
    CONSTRAINT ck_shop_order_currency CHECK (char_length(total_currency) = 3),
    CONSTRAINT ck_shop_order_status CHECK (status IN (
        'DRAFT', 'PENDING_PAYMENT', 'PAID', 'PROCESSING',
        'COMPLETED', 'CANCELLED', 'EXPIRED', 'REFUNDED'
    ))
);

CREATE INDEX idx_shop_order_customer_created
    ON shop_orders (customer_user_id, created_at);
CREATE INDEX idx_shop_order_status_created
    ON shop_orders (status, created_at);

CREATE TABLE shop_order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES shop_orders(id) ON DELETE CASCADE,
    product_id bigint NOT NULL,
    product_name varchar(200) NOT NULL,
    product_variant_id bigint,
    variant_name varchar(160),
    sku varchar(100),
    unit_price_amount_cents bigint NOT NULL,
    unit_price_currency char(3) NOT NULL,
    quantity integer NOT NULL,
    stock_reserved boolean NOT NULL DEFAULT false,
    line_total_amount_cents bigint NOT NULL,
    line_total_currency char(3) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_shop_order_item_quantity CHECK (quantity > 0),
    CONSTRAINT ck_shop_order_item_unit_price CHECK (unit_price_amount_cents >= 0),
    CONSTRAINT ck_shop_order_item_line_total CHECK (line_total_amount_cents >= 0),
    CONSTRAINT ck_shop_order_item_currency CHECK (
        unit_price_currency = line_total_currency
        AND char_length(unit_price_currency) = 3
    )
);

CREATE INDEX idx_shop_order_item_order ON shop_order_items (order_id);
CREATE INDEX idx_shop_order_item_product ON shop_order_items (product_id);

CREATE TABLE shop_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES shop_orders(id) ON DELETE RESTRICT,
    status varchar(32) NOT NULL,
    expected_amount_cents bigint NOT NULL,
    expected_currency char(3) NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_shop_payment_order UNIQUE (order_id),
    CONSTRAINT ck_shop_payment_amount CHECK (expected_amount_cents >= 0),
    CONSTRAINT ck_shop_payment_currency CHECK (char_length(expected_currency) = 3),
    CONSTRAINT ck_shop_payment_status CHECK (status IN (
        'CREATED', 'PENDING', 'SUCCEEDED', 'FAILED',
        'CANCELLED', 'REFUNDED'
    ))
);

CREATE INDEX idx_shop_payment_status_updated
    ON shop_payments (status, updated_at);

CREATE TABLE shop_payment_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id bigint NOT NULL REFERENCES shop_payments(id) ON DELETE CASCADE,
    provider_key varchar(80) NOT NULL,
    status varchar(32) NOT NULL,
    amount_cents bigint NOT NULL,
    currency char(3) NOT NULL,
    external_payment_id varchar(255),
    redirect_url varchar(2048),
    idempotency_key varchar(100) NOT NULL,
    failure_reason varchar(500),
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_shop_attempt_idempotency UNIQUE (payment_id, idempotency_key),
    CONSTRAINT uk_shop_attempt_provider_external UNIQUE (provider_key, external_payment_id),
    CONSTRAINT ck_shop_attempt_amount CHECK (amount_cents >= 0),
    CONSTRAINT ck_shop_attempt_currency CHECK (char_length(currency) = 3),
    CONSTRAINT ck_shop_attempt_status CHECK (status IN (
        'CREATED', 'PENDING', 'SUCCEEDED', 'FAILED',
        'CANCELLED', 'REFUNDED'
    ))
);

CREATE INDEX idx_shop_attempt_payment_status
    ON shop_payment_attempts (payment_id, status);
