ALTER TABLE shop_orders
    ADD COLUMN IF NOT EXISTS refund_requested boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_shop_order_refund_requested
    ON shop_orders (refund_requested, created_at);

CREATE TABLE IF NOT EXISTS shop_order_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES shop_orders(id) ON DELETE CASCADE,
    sender_user_id bigint,
    sender_type varchar(32) NOT NULL,
    content varchar(2000) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_shop_order_message_sender CHECK (sender_type IN ('CUSTOMER', 'SHOP_MANAGER')),
    CONSTRAINT ck_shop_order_message_content CHECK (char_length(trim(content)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_shop_order_message_order_created
    ON shop_order_messages (order_id, created_at, id);
