spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: benevoles.nepasrepondre@gmail.com
    password: lzaepihxmwnnpaur
    properties.mail.smtp:
      ssl.trust: smtp.gmail.com
      auth: true
      starttls.enable: true
  logging:
    file: /var/java_benevoles.log
    level:
      com.wild.corp: WARN
      root: WARN
      org.springframework:
        web: WARN
        jdbc.core.JdbcTemplate: WARN
        jdbc.core.StatementCreatorUtils: WARN
      org.hibernate: WARN
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000