spring:
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: alod.section.fete@gmail.com
    password: wqshdryblzispmbq
    properties.mail.smtp:
      ssl.trust: smtp.gmail.com
      auth: true
      starttls.enable: true
  logging:
    file: /var/java_asso.log
    level:
      com.wild.corp: WARN
      root: WARN
      org.springframework:
        web: WARN
        jdbc.core.JdbcTemplate: WARN
        jdbc.core.StatementCreatorUtils: WARN
      org.hibernate: WARN
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
server:
  app:
    jwtSecret: seCretForEVER5558
    jwtExpirationMs: 86400000
    fill_adherents: true
    fill_activites: true
  name: localhost:4200