package com.wild.corp.adhesion.models;

public enum ERole {
  ROLE_USER,
  ROLE_SECRETAIRE,
  ROLE_BUREAU,
  ROLE_MEMBRECA,
  ROLE_ADMIN,
  ROLE_COMPTABLE,
  ROLE_ENCADRANT,
  ROLE_REFERENT,
  ROLE_RESPONSABLE_BOUTIQUE
}
